### ISSUE TITLE
感谢老哥分享，19-09-4，把最后一行的sort去掉就没错误了，还是超时，但感觉heap加banlist已经是优化的极限了

### ISSUE THREAD

**Issue by storyandwine** [soyan1999/ccf-csp-python#1]

**Comment by storyandwine** [comment]
既然他的ask最大只有100，那是不是可以只维护一个长度为100的队列呢？

**Comment by soyan1999** [comment]
感谢提醒，已修改，虽然我也不知道为什么去掉sort就对了，感觉还是题目有点问题。
程序优化到最好跑不完很正常，考试时python是c++十倍时间。
维护长度100的队列应该对程序没什么优化的吧。
